project:
  type: website
  output-dir: docs

website:
  title: "Saifuddin86.github.io"
  sidebar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



